services:
  web-client:
    container_name: kebab-web-client
    build:
      context: ../web-client
    ports: 
      - 4200:4200
    develop:
      watch:
        - action: rebuild
          path: ../web-client
    depends_on:
      - backend-service

  backend-service:
    container_name: kebab-backend-service
    build:
      context: ../backend-service
    ports:
      - "5243:80"
    develop:
      watch:
        - action: rebuild
          path: ../backend-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - mongodb

  mongodb:
    container_name: kebab-mongodb
    image: mongo:8.0.1
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: kebab-innopolis

volumes:
  mongodb:
